name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get install doxygen -y
          sudo apt-get install graphviz -y

      - name: Build documentation
        working-directory: ${{ github.workspace }}
        run: |
          mkdir build
          cd build
          cmake -D ALTRO_BUILD_DOCS=ON ..
          cmake --build . --target altro_docs 

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/build/docs/html
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}